# [user@]hostname or a URI of the form ssh://[user@]hostname[:port.]. If user is empty 'root' will be used.
destination = "test@0.0.0.0:8000"

[deb]
packages = ["dnsutils", "neovim"] 

[[file]]
destination = "/tmp/test"
content = "This is a test"
